SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'boto3') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'boto3' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 38880 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'boto3' AND date >= '2023-06-23'::Date - toIntervalDay(84) AND date  <= '2023-06-23'::Date - toIntervalDay(39) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(84) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(39) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'boto3' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'urllib3') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'urllib3' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 3456 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'urllib3' AND date >= '2023-06-23'::Date - toIntervalDay(17) AND date  <= '2023-06-23'::Date - toIntervalDay(13) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(17) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(13) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'urllib3' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'requests') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'requests' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 8640 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'requests' AND date >= '2023-06-23'::Date - toIntervalDay(22) AND date  <= '2023-06-23'::Date - toIntervalDay(12) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(22) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(12) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'requests' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'botocore') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'botocore' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 24192 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'botocore' AND date >= '2023-06-23'::Date - toIntervalDay(56) AND date  <= '2023-06-23'::Date - toIntervalDay(28) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(56) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(28) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'botocore' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'charset-normalizer') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'charset-normalizer' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 6048 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'charset-normalizer' AND date >= '2023-06-23'::Date - toIntervalDay(77) AND date  <= '2023-06-23'::Date - toIntervalDay(70) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(77) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(70) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'charset-normalizer' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'setuptools') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'setuptools' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 66528 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'setuptools' AND date >= '2023-06-23'::Date - toIntervalDay(90) AND date  <= '2023-06-23'::Date - toIntervalDay(13) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(90) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(13) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'setuptools' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'idna') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'idna' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 11232 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'idna' AND date >= '2023-06-23'::Date - toIntervalDay(60) AND date  <= '2023-06-23'::Date - toIntervalDay(47) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(60) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(47) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'idna' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'certifi') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'certifi' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 6048 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'certifi' AND date >= '2023-06-23'::Date - toIntervalDay(50) AND date  <= '2023-06-23'::Date - toIntervalDay(43) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(50) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(43) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'certifi' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 's3transfer') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 's3transfer' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 17280 second) as period, count() as count, system.name as system FROM pypi WHERE project = 's3transfer' AND date >= '2023-06-23'::Date - toIntervalDay(71) AND date  <= '2023-06-23'::Date - toIntervalDay(51) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(71) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(51) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 's3transfer' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'python-dateutil') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'python-dateutil' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 47520 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'python-dateutil' AND date >= '2023-06-23'::Date - toIntervalDay(68) AND date  <= '2023-06-23'::Date - toIntervalDay(13) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(68) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(13) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'python-dateutil' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'awscli') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'awscli' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 864 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'awscli' AND date >= '2023-06-23'::Date - toIntervalDay(15) AND date  <= '2023-06-23'::Date - toIntervalDay(14) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(15) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(14) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'awscli' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'typing-extensions') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'typing-extensions' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 1728 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'typing-extensions' AND date >= '2023-06-23'::Date - toIntervalDay(8) AND date  <= '2023-06-23'::Date - toIntervalDay(6) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(8) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(6) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'typing-extensions' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'six') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'six' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 21600 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'six' AND date >= '2023-06-23'::Date - toIntervalDay(25) AND date  <= '2023-06-23'::Date - toIntervalDay(0) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(25) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(0) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'six' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pyyaml') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyyaml' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 33696 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pyyaml' AND date >= '2023-06-23'::Date - toIntervalDay(40) AND date  <= '2023-06-23'::Date - toIntervalDay(1) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(40) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(1) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyyaml' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'google-api-core') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'google-api-core' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 45792 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'google-api-core' AND date >= '2023-06-23'::Date - toIntervalDay(70) AND date  <= '2023-06-23'::Date - toIntervalDay(17) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(70) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(17) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'google-api-core' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'wheel') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'wheel' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 27648 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'wheel' AND date >= '2023-06-23'::Date - toIntervalDay(84) AND date  <= '2023-06-23'::Date - toIntervalDay(52) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(84) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(52) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'wheel' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'cryptography') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'cryptography' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 27648 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'cryptography' AND date >= '2023-06-23'::Date - toIntervalDay(80) AND date  <= '2023-06-23'::Date - toIntervalDay(48) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(80) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(48) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'cryptography' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'packaging') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'packaging' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 1728 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'packaging' AND date >= '2023-06-23'::Date - toIntervalDay(57) AND date  <= '2023-06-23'::Date - toIntervalDay(55) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(57) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(55) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'packaging' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'numpy') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'numpy' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 7776 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'numpy' AND date >= '2023-06-23'::Date - toIntervalDay(25) AND date  <= '2023-06-23'::Date - toIntervalDay(16) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(25) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(16) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'numpy' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pip') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pip' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 21600 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pip' AND date >= '2023-06-23'::Date - toIntervalDay(28) AND date  <= '2023-06-23'::Date - toIntervalDay(3) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(28) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(3) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pip' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'jmespath') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'jmespath' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 25056 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'jmespath' AND date >= '2023-06-23'::Date - toIntervalDay(68) AND date  <= '2023-06-23'::Date - toIntervalDay(39) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(68) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(39) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'jmespath' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'importlib-metadata') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'importlib-metadata' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 20736 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'importlib-metadata' AND date >= '2023-06-23'::Date - toIntervalDay(82) AND date  <= '2023-06-23'::Date - toIntervalDay(58) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(82) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(58) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'importlib-metadata' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'zipp') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'zipp' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 864 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'zipp' AND date >= '2023-06-23'::Date - toIntervalDay(32) AND date  <= '2023-06-23'::Date - toIntervalDay(31) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(32) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(31) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'zipp' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'click') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'click' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 55296 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'click' AND date >= '2023-06-23'::Date - toIntervalDay(82) AND date  <= '2023-06-23'::Date - toIntervalDay(18) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(82) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(18) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'click' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pyasn1') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyasn1' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 65664 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pyasn1' AND date >= '2023-06-23'::Date - toIntervalDay(78) AND date  <= '2023-06-23'::Date - toIntervalDay(2) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(78) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(2) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyasn1' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'colorama') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'colorama' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 9504 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'colorama' AND date >= '2023-06-23'::Date - toIntervalDay(61) AND date  <= '2023-06-23'::Date - toIntervalDay(50) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(61) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(50) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'colorama' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'protobuf') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'protobuf' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 1728 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'protobuf' AND date >= '2023-06-23'::Date - toIntervalDay(2) AND date  <= '2023-06-23'::Date - toIntervalDay(0) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(2) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(0) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'protobuf' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'rsa') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'rsa' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 8640 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'rsa' AND date >= '2023-06-23'::Date - toIntervalDay(28) AND date  <= '2023-06-23'::Date - toIntervalDay(18) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(28) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(18) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'rsa' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'attrs') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'attrs' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 6912 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'attrs' AND date >= '2023-06-23'::Date - toIntervalDay(35) AND date  <= '2023-06-23'::Date - toIntervalDay(27) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(35) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(27) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'attrs' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pytz') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pytz' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 27648 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pytz' AND date >= '2023-06-23'::Date - toIntervalDay(67) AND date  <= '2023-06-23'::Date - toIntervalDay(35) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(67) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(35) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pytz' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pandas') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pandas' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 28512 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pandas' AND date >= '2023-06-23'::Date - toIntervalDay(46) AND date  <= '2023-06-23'::Date - toIntervalDay(13) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(46) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(13) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pandas' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'markupsafe') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'markupsafe' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 6048 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'markupsafe' AND date >= '2023-06-23'::Date - toIntervalDay(17) AND date  <= '2023-06-23'::Date - toIntervalDay(10) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(17) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(10) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'markupsafe' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'jinja2') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'jinja2' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 12960 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'jinja2' AND date >= '2023-06-23'::Date - toIntervalDay(16) AND date  <= '2023-06-23'::Date - toIntervalDay(1) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(16) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(1) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'jinja2' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'cffi') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'cffi' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 57024 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'cffi' AND date >= '2023-06-23'::Date - toIntervalDay(74) AND date  <= '2023-06-23'::Date - toIntervalDay(8) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(74) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(8) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'cffi' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pyjwt') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyjwt' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 31968 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pyjwt' AND date >= '2023-06-23'::Date - toIntervalDay(72) AND date  <= '2023-06-23'::Date - toIntervalDay(35) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(72) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(35) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyjwt' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pycparser') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pycparser' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 50112 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pycparser' AND date >= '2023-06-23'::Date - toIntervalDay(58) AND date  <= '2023-06-23'::Date - toIntervalDay(0) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(58) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(0) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pycparser' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'aiobotocore') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'aiobotocore' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 12960 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'aiobotocore' AND date >= '2023-06-23'::Date - toIntervalDay(29) AND date  <= '2023-06-23'::Date - toIntervalDay(14) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(29) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(14) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'aiobotocore' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 's3fs') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 's3fs' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 5184 second) as period, count() as count, system.name as system FROM pypi WHERE project = 's3fs' AND date >= '2023-06-23'::Date - toIntervalDay(19) AND date  <= '2023-06-23'::Date - toIntervalDay(13) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(19) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(13) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 's3fs' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'fsspec') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'fsspec' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 21600 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'fsspec' AND date >= '2023-06-23'::Date - toIntervalDay(50) AND date  <= '2023-06-23'::Date - toIntervalDay(25) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(50) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(25) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'fsspec' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'grpcio-status') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'grpcio-status' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 59616 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'grpcio-status' AND date >= '2023-06-23'::Date - toIntervalDay(89) AND date  <= '2023-06-23'::Date - toIntervalDay(20) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(89) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(20) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'grpcio-status' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'googleapis-common-protos') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'googleapis-common-protos' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 63072 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'googleapis-common-protos' AND date >= '2023-06-23'::Date - toIntervalDay(77) AND date  <= '2023-06-23'::Date - toIntervalDay(4) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(77) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(4) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'googleapis-common-protos' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'docutils') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'docutils' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 36288 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'docutils' AND date >= '2023-06-23'::Date - toIntervalDay(56) AND date  <= '2023-06-23'::Date - toIntervalDay(14) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(56) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(14) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'docutils' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'google-auth') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'google-auth' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 2592 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'google-auth' AND date >= '2023-06-23'::Date - toIntervalDay(7) AND date  <= '2023-06-23'::Date - toIntervalDay(4) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(7) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(4) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'google-auth' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'oauthlib') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'oauthlib' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 22464 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'oauthlib' AND date >= '2023-06-23'::Date - toIntervalDay(89) AND date  <= '2023-06-23'::Date - toIntervalDay(63) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(89) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(63) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'oauthlib' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'tomli') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'tomli' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 2592 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'tomli' AND date >= '2023-06-23'::Date - toIntervalDay(12) AND date  <= '2023-06-23'::Date - toIntervalDay(9) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(12) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(9) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'tomli' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'wrapt') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'wrapt' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 4320 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'wrapt' AND date >= '2023-06-23'::Date - toIntervalDay(8) AND date  <= '2023-06-23'::Date - toIntervalDay(3) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(8) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(3) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'wrapt' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'cachetools') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'cachetools' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 45792 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'cachetools' AND date >= '2023-06-23'::Date - toIntervalDay(73) AND date  <= '2023-06-23'::Date - toIntervalDay(20) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(73) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(20) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'cachetools' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pyparsing') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyparsing' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 21600 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pyparsing' AND date >= '2023-06-23'::Date - toIntervalDay(48) AND date  <= '2023-06-23'::Date - toIntervalDay(23) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(48) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(23) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyparsing' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'werkzeug') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'werkzeug' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 29376 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'werkzeug' AND date >= '2023-06-23'::Date - toIntervalDay(49) AND date  <= '2023-06-23'::Date - toIntervalDay(15) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(49) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(15) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'werkzeug' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'sqlalchemy') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'sqlalchemy' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 10368 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'sqlalchemy' AND date >= '2023-06-23'::Date - toIntervalDay(44) AND date  <= '2023-06-23'::Date - toIntervalDay(32) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(44) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(32) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'sqlalchemy' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'requests-oauthlib') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'requests-oauthlib' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 39744 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'requests-oauthlib' AND date >= '2023-06-23'::Date - toIntervalDay(49) AND date  <= '2023-06-23'::Date - toIntervalDay(3) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(49) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(3) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'requests-oauthlib' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'multidict') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'multidict' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 12096 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'multidict' AND date >= '2023-06-23'::Date - toIntervalDay(69) AND date  <= '2023-06-23'::Date - toIntervalDay(55) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(69) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(55) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'multidict' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'yarl') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'yarl' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 8640 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'yarl' AND date >= '2023-06-23'::Date - toIntervalDay(17) AND date  <= '2023-06-23'::Date - toIntervalDay(7) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(17) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(7) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'yarl' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pyarrow') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyarrow' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 27648 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pyarrow' AND date >= '2023-06-23'::Date - toIntervalDay(53) AND date  <= '2023-06-23'::Date - toIntervalDay(21) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(53) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(21) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyarrow' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'jsonschema') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'jsonschema' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 17280 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'jsonschema' AND date >= '2023-06-23'::Date - toIntervalDay(84) AND date  <= '2023-06-23'::Date - toIntervalDay(64) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(84) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(64) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'jsonschema' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'platformdirs') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'platformdirs' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 22464 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'platformdirs' AND date >= '2023-06-23'::Date - toIntervalDay(27) AND date  <= '2023-06-23'::Date - toIntervalDay(1) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(27) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(1) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'platformdirs' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'async-timeout') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'async-timeout' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 4320 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'async-timeout' AND date >= '2023-06-23'::Date - toIntervalDay(5) AND date  <= '2023-06-23'::Date - toIntervalDay(0) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(5) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(0) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'async-timeout' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'aiohttp') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'aiohttp' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 5184 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'aiohttp' AND date >= '2023-06-23'::Date - toIntervalDay(9) AND date  <= '2023-06-23'::Date - toIntervalDay(3) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(9) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(3) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'aiohttp' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'isodate') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'isodate' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 12960 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'isodate' AND date >= '2023-06-23'::Date - toIntervalDay(22) AND date  <= '2023-06-23'::Date - toIntervalDay(7) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(22) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(7) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'isodate' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'psutil') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'psutil' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 27648 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'psutil' AND date >= '2023-06-23'::Date - toIntervalDay(60) AND date  <= '2023-06-23'::Date - toIntervalDay(28) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(60) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(28) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'psutil' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pydantic') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pydantic' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 12096 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pydantic' AND date >= '2023-06-23'::Date - toIntervalDay(14) AND date  <= '2023-06-23'::Date - toIntervalDay(0) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(14) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(0) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pydantic' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'decorator') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'decorator' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 12960 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'decorator' AND date >= '2023-06-23'::Date - toIntervalDay(21) AND date  <= '2023-06-23'::Date - toIntervalDay(6) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(21) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(6) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'decorator' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pyasn1-modules') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyasn1-modules' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 25056 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pyasn1-modules' AND date >= '2023-06-23'::Date - toIntervalDay(45) AND date  <= '2023-06-23'::Date - toIntervalDay(16) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(45) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(16) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyasn1-modules' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'soupsieve') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'soupsieve' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 23328 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'soupsieve' AND date >= '2023-06-23'::Date - toIntervalDay(87) AND date  <= '2023-06-23'::Date - toIntervalDay(60) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(87) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(60) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'soupsieve' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'flask') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'flask' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 23328 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'flask' AND date >= '2023-06-23'::Date - toIntervalDay(80) AND date  <= '2023-06-23'::Date - toIntervalDay(53) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(80) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(53) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'flask' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pluggy') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pluggy' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 4320 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pluggy' AND date >= '2023-06-23'::Date - toIntervalDay(11) AND date  <= '2023-06-23'::Date - toIntervalDay(6) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(11) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(6) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pluggy' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pytest') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pytest' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 28512 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pytest' AND date >= '2023-06-23'::Date - toIntervalDay(38) AND date  <= '2023-06-23'::Date - toIntervalDay(5) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(38) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(5) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pytest' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'beautifulsoup4') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'beautifulsoup4' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 2592 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'beautifulsoup4' AND date >= '2023-06-23'::Date - toIntervalDay(82) AND date  <= '2023-06-23'::Date - toIntervalDay(79) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(82) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(79) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'beautifulsoup4' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'lxml') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'lxml' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 57888 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'lxml' AND date >= '2023-06-23'::Date - toIntervalDay(86) AND date  <= '2023-06-23'::Date - toIntervalDay(19) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(86) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(19) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'lxml' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'filelock') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'filelock' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 13824 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'filelock' AND date >= '2023-06-23'::Date - toIntervalDay(22) AND date  <= '2023-06-23'::Date - toIntervalDay(6) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(22) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(6) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'filelock' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'grpcio') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'grpcio' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 21600 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'grpcio' AND date >= '2023-06-23'::Date - toIntervalDay(25) AND date  <= '2023-06-23'::Date - toIntervalDay(0) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(25) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(0) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'grpcio' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'greenlet') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'greenlet' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 45792 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'greenlet' AND date >= '2023-06-23'::Date - toIntervalDay(54) AND date  <= '2023-06-23'::Date - toIntervalDay(1) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(54) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(1) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'greenlet' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'frozenlist') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'frozenlist' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 49248 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'frozenlist' AND date >= '2023-06-23'::Date - toIntervalDay(68) AND date  <= '2023-06-23'::Date - toIntervalDay(11) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(68) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(11) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'frozenlist' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'coverage') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'coverage' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 6912 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'coverage' AND date >= '2023-06-23'::Date - toIntervalDay(8) AND date  <= '2023-06-23'::Date - toIntervalDay(0) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(8) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(0) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'coverage' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'aiosignal') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'aiosignal' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 7776 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'aiosignal' AND date >= '2023-06-23'::Date - toIntervalDay(29) AND date  <= '2023-06-23'::Date - toIntervalDay(20) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(29) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(20) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'aiosignal' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'azure-core') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'azure-core' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 30240 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'azure-core' AND date >= '2023-06-23'::Date - toIntervalDay(58) AND date  <= '2023-06-23'::Date - toIntervalDay(23) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(58) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(23) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'azure-core' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'scipy') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'scipy' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 12096 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'scipy' AND date >= '2023-06-23'::Date - toIntervalDay(38) AND date  <= '2023-06-23'::Date - toIntervalDay(24) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(38) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(24) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'scipy' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pillow') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pillow' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 25056 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pillow' AND date >= '2023-06-23'::Date - toIntervalDay(29) AND date  <= '2023-06-23'::Date - toIntervalDay(0) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(29) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(0) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pillow' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'tqdm') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'tqdm' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 8640 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'tqdm' AND date >= '2023-06-23'::Date - toIntervalDay(17) AND date  <= '2023-06-23'::Date - toIntervalDay(7) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(17) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(7) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'tqdm' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pyrsistent') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyrsistent' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 2592 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pyrsistent' AND date >= '2023-06-23'::Date - toIntervalDay(16) AND date  <= '2023-06-23'::Date - toIntervalDay(13) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(16) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(13) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyrsistent' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'virtualenv') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'virtualenv' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 31104 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'virtualenv' AND date >= '2023-06-23'::Date - toIntervalDay(76) AND date  <= '2023-06-23'::Date - toIntervalDay(40) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(76) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(40) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'virtualenv' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'et-xmlfile') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'et-xmlfile' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 864 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'et-xmlfile' AND date >= '2023-06-23'::Date - toIntervalDay(5) AND date  <= '2023-06-23'::Date - toIntervalDay(4) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(5) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(4) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'et-xmlfile' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'openpyxl') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'openpyxl' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 18144 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'openpyxl' AND date >= '2023-06-23'::Date - toIntervalDay(34) AND date  <= '2023-06-23'::Date - toIntervalDay(13) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(34) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(13) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'openpyxl' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'importlib-resources') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'importlib-resources' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 35424 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'importlib-resources' AND date >= '2023-06-23'::Date - toIntervalDay(77) AND date  <= '2023-06-23'::Date - toIntervalDay(36) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(77) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(36) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'importlib-resources' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pyopenssl') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyopenssl' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 29376 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pyopenssl' AND date >= '2023-06-23'::Date - toIntervalDay(73) AND date  <= '2023-06-23'::Date - toIntervalDay(39) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(73) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(39) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pyopenssl' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'iniconfig') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'iniconfig' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 31104 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'iniconfig' AND date >= '2023-06-23'::Date - toIntervalDay(37) AND date  <= '2023-06-23'::Date - toIntervalDay(1) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(37) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(1) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'iniconfig' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pygments') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pygments' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 30240 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pygments' AND date >= '2023-06-23'::Date - toIntervalDay(39) AND date  <= '2023-06-23'::Date - toIntervalDay(4) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(39) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(4) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pygments' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'chardet') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'chardet' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 6912 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'chardet' AND date >= '2023-06-23'::Date - toIntervalDay(10) AND date  <= '2023-06-23'::Date - toIntervalDay(2) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(10) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(2) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'chardet' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'asn1crypto') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'asn1crypto' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 10368 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'asn1crypto' AND date >= '2023-06-23'::Date - toIntervalDay(31) AND date  <= '2023-06-23'::Date - toIntervalDay(19) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(31) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(19) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'asn1crypto' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'itsdangerous') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'itsdangerous' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 16416 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'itsdangerous' AND date >= '2023-06-23'::Date - toIntervalDay(31) AND date  <= '2023-06-23'::Date - toIntervalDay(12) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(31) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(12) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'itsdangerous' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'exceptiongroup') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'exceptiongroup' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 22464 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'exceptiongroup' AND date >= '2023-06-23'::Date - toIntervalDay(58) AND date  <= '2023-06-23'::Date - toIntervalDay(32) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(58) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(32) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'exceptiongroup' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'websocket-client') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'websocket-client' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 11232 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'websocket-client' AND date >= '2023-06-23'::Date - toIntervalDay(64) AND date  <= '2023-06-23'::Date - toIntervalDay(51) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(64) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(51) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'websocket-client' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'tabulate') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'tabulate' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 15552 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'tabulate' AND date >= '2023-06-23'::Date - toIntervalDay(36) AND date  <= '2023-06-23'::Date - toIntervalDay(18) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(36) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(18) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'tabulate' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'google-api-python-client') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'google-api-python-client' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 38016 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'google-api-python-client' AND date >= '2023-06-23'::Date - toIntervalDay(59) AND date  <= '2023-06-23'::Date - toIntervalDay(15) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(59) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(15) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'google-api-python-client' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'requests-toolbelt') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'requests-toolbelt' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 12096 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'requests-toolbelt' AND date >= '2023-06-23'::Date - toIntervalDay(19) AND date  <= '2023-06-23'::Date - toIntervalDay(5) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(19) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(5) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'requests-toolbelt' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'google-cloud-core') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'google-cloud-core' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 32832 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'google-cloud-core' AND date >= '2023-06-23'::Date - toIntervalDay(41) AND date  <= '2023-06-23'::Date - toIntervalDay(3) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(41) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(3) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'google-cloud-core' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'mypy-extensions') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'mypy-extensions' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 39744 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'mypy-extensions' AND date >= '2023-06-23'::Date - toIntervalDay(56) AND date  <= '2023-06-23'::Date - toIntervalDay(10) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(56) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(10) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'mypy-extensions' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'pynacl') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pynacl' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 27648 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'pynacl' AND date >= '2023-06-23'::Date - toIntervalDay(60) AND date  <= '2023-06-23'::Date - toIntervalDay(28) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(60) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(28) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'pynacl' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'google-cloud-storage') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'google-cloud-storage' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 47520 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'google-cloud-storage' AND date >= '2023-06-23'::Date - toIntervalDay(69) AND date  <= '2023-06-23'::Date - toIntervalDay(14) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(69) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(14) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'google-cloud-storage' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
SELECT date as day, system.name as system, count() AS count FROM pypi WHERE (project = 'psycopg2-binary') AND (date >= '2023-06-23'::Date - toIntervalDay(90)) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'psycopg2-binary' GROUP BY system ORDER BY count() DESC LIMIT 10) GROUP BY day, system ORDER BY day ASC, count DESC
SELECT toStartOfInterval(timestamp, INTERVAL 6912 second) as period, count() as count, system.name as system FROM pypi WHERE project = 'psycopg2-binary' AND date >= '2023-06-23'::Date - toIntervalDay(9) AND date  <= '2023-06-23'::Date - toIntervalDay(1) AND timestamp >= '2023-06-23 08:33:59'::DateTime - toIntervalDay(9) AND timestamp  <= '2023-06-23 08:33:59'::DateTime - toIntervalDay(1) AND system IN ( SELECT system.name as system FROM pypi WHERE system != '' AND project = 'psycopg2-binary' GROUP BY system ORDER BY count() DESC LIMIT 10)GROUP BY period, system ORDER BY period ASC, count DESC
